/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opmanagementsystem;
import java.sql.*;
import javax.swing.JOptionPane;
public class UserLoginPage extends javax.swing.JFrame {

    Connection conn;
    ResultSet res;
    PreparedStatement pst;
    String resname;
    public UserLoginPage() {
        initComponents();
        conn = DataBase.DBconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uusername = new javax.swing.JTextField();
        upassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uutype = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Oswald", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        uusername.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jPanel1.add(uusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 408, 40));

        upassword.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jPanel1.add(upassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 408, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-administrator-male-30.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 30, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-lock-24.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        uutype.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        uutype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Receptionist", "Doctor", "Pharmasist" }));
        uutype.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel1.add(uutype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 408, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-account-24.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        login.setBackground(new java.awt.Color(0, 153, 0));
        login.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-login-rounded-24.png"))); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 661, 128, 53));

        exit.setBackground(new java.awt.Color(255, 51, 51));
        exit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-logout-rounded-left-24.png"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 661, 117, 53));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pina-messina-iIDiRMITYik-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, -1, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String name = uusername.getText();
        String pass = upassword.getText();
        String utype = uutype.getSelectedItem().toString();
        try
        {
            String sql = "SELECT * FROM user WHERE username = ? AND password = ? AND usertype = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, name);
            pst.setString(2, pass);
            pst.setString(3, utype);
            res = pst.executeQuery();
            if(res.next())
            {
                String resname = res.getString("usertype");
                 switch(resname)
           {
                case "Receptionist" :
                    ReceptionistDashBordPage recep = new ReceptionistDashBordPage();
                   recep.setVisible(true);
                   uusername.setText("");
                   upassword.setText("");
                   uutype.setSelectedIndex(-1);
                   uusername.requestFocus();
                    break;
                case "Doctor" :
                   int id = res.getInt("id");
                   DoctorDashBordPage docpage = new DoctorDashBordPage(id);
                   docpage.setVisible(true);
                   uusername.setText("");
                   upassword.setText("");
                   uutype.setSelectedIndex(-1);
                   uusername.requestFocus();
                   break;
                case "Pharmasist" :
                    PharmasistDashbordPage px = new PharmasistDashbordPage();
                    px.setVisible(true);
                    uusername.setText("");
                    upassword.setText("");
                    uutype.setSelectedIndex(-1);
                    uusername.requestFocus();
                    break;
              default :
                  JOptionPane.showMessageDialog(null,"Username and Password Incorrect !");
                   break;
           }
            }
            else {
                JOptionPane.showMessageDialog(null,"Username and Password Incorrect !");
                uusername.setText("");
                   upassword.setText("");
                   uutype.setSelectedIndex(-1);
                   uusername.requestFocus();
            }
        } catch(Exception ex)
        {
            System.out.println("Something Went wrong !" + ex);
        }
        
    }//GEN-LAST:event_loginActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField upassword;
    private javax.swing.JTextField uusername;
    private javax.swing.JComboBox uutype;
    // End of variables declaration//GEN-END:variables
}
